### ISSUE TITLE
需要一个api能把点阵做成面

### ISSUE THREAD

**Issue by HenryMaoETA** [anycad/anycad.rapid.net.sample#1]
就像以前anycad的MakeSurfaceFromPoints

**Comment by anycad** [comment]
Added SurfaceBuilder API and sample code Geometry_Surface.cs

`            Random rand = new Random();
            GPntList points = new GPntList();
            for (int ii = 0; ii < 5; ++ii)
                for (int jj = 0; jj < 5; ++jj)
                {
                    points.Add(new GPnt(ii, jj, rand.NextDouble()));
                }

            var surf = SurfaceBuilder.PointsToBSplineSurface(points, 5);`

**Comment by HenryMaoETA** [comment]
那如果是5x10的点阵呢？

**Comment by anycad** [comment]
> 那如果是5x10的点阵呢？

也是支持的
for (int ii = 0; ii < 10; ++ii)
for (int jj = 0; jj < 5; ++jj)
{
points.Add(new GPnt(ii, jj, rand.NextDouble()));
}
var surf = SurfaceBuilder.PointsToBSplineSurface(points, 5);

**Comment by HenryMaoETA** [comment]
谢谢
