### ISSUE TITLE
How do I remove some object from display?

### ISSUE THREAD

**Issue by uzername** [anycad/anycad.rapid.net.sample#10]
I can display an object on Render Window using a ShowShape call.

```
            var box = ShapeBuilder.MakeBox(GP.XOY(), 10, 20, 30);
            render.ShowShape(box, Vector3.Green);
```

How do I remove something from display?

**Comment by anycad** [comment]
You can use the Scene API to remove the node:
`
var id = box.GetUuid();
render.GetScene().RemoveNode(id);
`
