### ISSUE TITLE
Constant calls to garbage collector are seen in profiling

### ISSUE THREAD

**Issue by uzername** [anycad/anycad.rapid.net.sample#13]
![image](https://user-images.githubusercontent.com/864126/95287255-182d9f80-086e-11eb-8e68-918b6efffb26.png)
I believe these constant calls to garbage collector are not good. Garbage collector is getting called too often. Seems like it is invoked every frame. May cause performance problems

**Comment by anycad** [comment]
@uzername Thanks for your suggestion. We will add AutoGarbageCollection property for RenderControl, and you can decide whether to close it.

**Comment by uzername** [comment]
A program also hangs in memory for about 1-2 minutes after closing a window. It may be a symptom of something wrong happening

**Comment by anycad** [comment]
RenderControl.AutoGarbageCollection = false to disable gc.

since v2020.10.15
