### ISSUE TITLE
增加字体显示功能

### ISSUE THREAD

**Issue by dm82402** [anycad/anycad.rapid.net.sample#2]
原有anycad中
            String fontName = "simhei.ttf";
            AnyCAD.Platform.Font font = GlobalInstance.FontManager.FindFont(fontName);
            if (font != null)
            {
                font.SetCharHeight(24);
                font.SetCharWdith(24);
                font.Update();
            }
可以指定显示的字体

而AnyCAD.Rapid版本中，缺乏这个功能
var fontMaterial = FontMaterial.Create("font-texture-1");
            fontMaterial.SetFaceSide(EnumFaceSide.DoubleSide);
            fontMaterial.SetColor(new Vector3(1, 1, 0));
            fontMaterial.SetBackground(new Vector3(0, 0, 1));
            fontMaterial.SetBillboard(true);

            var dim = fontMaterial.SetText("Hello 世界!", 32);
            var shape = GeometryBuilder.CreatePlane(dim.x * 0.1f, dim.y * 0.1f);
            var node = new PrimitiveSceneNode(shape, fontMaterial);
            node.SetPickable(false);

            render.ShowSceneNode(node);

**Comment by anycad** [comment]
Add user defined Font API:

`FontManager.Instance().AddFont("LS", @"C:\Windows\Fonts\STLITI.TTF");`

`var dim = fontMaterial.SetText("Hello 世界!", 128, "LS");`

"LS" the Font Name/ID
