### ISSUE TITLE
Highlighting of plane feels wrong

### ISSUE THREAD

**Issue by uzername** [anycad/anycad.rapid.net.sample#20]
I am including picture here. I am hovering mouse over blue box, which is located behind green one. 

![image](https://user-images.githubusercontent.com/864126/96419977-8e7eba00-11fd-11eb-8e89-e810a6a685c0.png)

As you can see, highlight is shown in front of green one, overlapping it. I think this may be related to how shader is written. And I think that highlight should not overwrite color of overlapped figures.

**Comment by anycad** [comment]
@uzername  Thanks for you feedback.
We will add method for SelectionManager.SetDepthTest to control the overriding behaviour of selected objects in the next release.

**Comment by uzername** [comment]
Also, I think that controlling color of highlight may be useful too.

**Comment by anycad** [comment]
Use renderView.GetContext().GetSelection().SetDepthTest(true) to enable depth testing.

**Comment by uzername** [comment]
It works.
