### ISSUE TITLE
无法加载和显示stl文件

### ISSUE THREAD

**Issue by wdzhangsl** [anycad/anycad.rapid.net.sample#22]
无法加载和显示stl文件
ASCII格式的和二进制格式的都不行

文件如下：
百度云盘

链接：https://pan.baidu.com/s/1jlqPt40ez5GOtkIjwcSzrg 
提取码：02ko 

链接：https://pan.baidu.com/s/15PClQ_79Xe6aIe47PM_Zrg 
提取码：ji6i

**Comment by anycad** [comment]
新版已经修复
