### ISSUE TITLE
Is it possible to configure input events in Anycad

### ISSUE THREAD

**Issue by uzername** [anycad/anycad.rapid.net.sample#26]
Hello. I want to be able to rotate with the right click mouse event, and not the left. Also, I'd like to know, is it possible in general to configure input behavior in Viewer pane? We would make User to be able to choose how they would pan, zoom and rotate the scene.

**Comment by anycad** [comment]
Yes，you can use ViewContext.SetPanButton(..), SetOrbitButton(..) to change the default behaviour.
