### ISSUE TITLE
AnyCAD.Rapid中ZoomAll()功能

### ISSUE THREAD

**Issue by dm82402** [anycad/anycad.rapid.net.sample#3]
原有anycad中有一个FitAll()方法，同时该方法让模型大小和3D显示区域显示一个合适的比例，而且可以在这个FitAll设置显示比例
现在ZoomAll()直接将模型显示到3D显示区域最大一个范围

能否实现原有anycad中有一个FitAll()方法达到的效果

**Comment by anycad** [comment]
ZoomAll增加参数来控制缩放比例，想要多大范围就显示多大范围

` mRenderView.ZoomAll(1.2f);`
