### ISSUE TITLE
TextNode效果问题

### ISSUE THREAD

**Issue by dm82402** [anycad/anycad.rapid.net.sample#4]
AnyCAD.Rapid中的FontMaterial所实现的效果跟原有Anycad中TextNode实现的效果不一样
由于需要在3D图像上做文字标注，原有在Anycad上使用的是TextNode，基本可以达到效果，但是
现有AnyCAD.Rapid中FontMaterial实现文字无法达到原来效果

**Comment by anycad** [comment]
增加TagNode2D API：

- 不跟随相机缩放
- 支持设置背景色，包括透明色
