### ISSUE TITLE
软件关闭时，报opengl32.dll问题。

### ISSUE THREAD

**Issue by ABoo1989** [anycad/anycad.rapid.net.sample#5]
0x00007FFD0FD20F95 (opengl32.dll) (LaserRanderMeas.exe 中)处有未经处理的异常: 0xC0000005: 读取位置 0x0000000000000A38 时发生访问冲突。
之前使用的0903的版本，更新0921版本后出现该问题。

**Comment by anycad** [comment]
Fixed in 20.10.27

**Comment by anycad** [comment]
static void Main()
        {
            **AnyCAD.Foundation.GlobalInstance.Initialize();**
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
            **AnyCAD.Foundation.GlobalInstance.Destroy();**
        }
