### ISSUE TITLE
功能需求：模型显示模式设置EnumDisplayStyle

### ISSUE THREAD

**Issue by ABoo1989** [anycad/anycad.rapid.net.sample#6]
以前的版本中可以设置模型的显示模式，如
renderView.SetDisplayMode((int)(EnumDisplayStyle.DS_Face|EnumDisplayStyle.DS_Realistic));
新版本中没有

**Comment by anycad** [comment]
增加DisplayFilter API：       
            renderView.ResetDisplayFilters();
            renderView.ClearDisplayFilter(EnumShapeFilter.Face);
            renderView.RequestDraw();
