### ISSUE TITLE
功能需求：拾取点

### ISSUE THREAD

**Issue by ABoo1989** [anycad/anycad.rapid.net.sample#7]
通过 var geometry = GeometryBuilder.CreatePoints(new Float32Array(mPositions), new Float32Array(mColors));
            var node = new PrimitiveSceneNode(geometry, material);
            node.SetPickable(false);
            mRenderView.ShowSceneNode(node);
可以添加单个点，也可以添加点云，但是无法在Render中拾取点。
希望拾取点可以通过点击鼠标左键单独拾取，也可以通过画矩形框进行多选。

**Comment by anycad** [comment]
新版本已经支持
