### ISSUE TITLE
How do I show grid lines in this edition of anycad sdk?

### ISSUE THREAD

**Issue by uzername** [anycad/anycad.rapid.net.sample#9]
In older edition of anycad SDK I could use:

`renderView.ShowWorkingGrid(bool)` from `AnyCAD.Presentation.RenderWindow3d` . 

But in anycad.rapid.net we use now AnyCAD.Forms.RenderControl which does not have such method.

**Comment by uzername** [comment]
Controlling grid in older version was counterintuitive; I remember, you had to operate with it like with a scene node, or something

I believe that in new edition of anycad it may be nice to have grid as subclass of TopoShape , with methods for setting up line width, line color (for primary and secondary lines), show-hide colored lines for axis; and then calling RequestUpdate after changing.

**Comment by anycad** [comment]
You can use ShowCoordinateGrid API to show hide coordinate grid:
`
mRenderView.ShowCoordinateGrid(bShowCoordinateGrid);
`

**Comment by uzername** [comment]
What is the API for controlling a grid look? I mean, number of cells, style of lines ? I believe, this should be in new issue.
